#!/bin/sh

### BEGIN INIT INFO
# Provides:          udev
# Required-Start:    mountvirtfs
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Start udevd, populate /dev and load drivers.
### END INIT INFO

export TZ=/etc/localtime

export ACTION=add

[ -e /dev/pts ] || mkdir -m 0755 /dev/pts
[ -e /dev/shm ] || mkdir -m 1777 /dev/shm

# trigger the sorted events
echo -e '\000\000\000\000' > /proc/sys/kernel/hotplug
/sbin/udevd -d

/sbin/udevadm control --env=STARTUP=1
/sbin/udevadm trigger --action=add --subsystem-nomatch=tty --subsystem-nomatch=mem \
					  --subsystem-nomatch=vc --subsystem-nomatch=vtconsole --subsystem-nomatch=misc \
					  --subsystem-nomatch=dcon --subsystem-nomatch=pci_bus  --subsystem-nomatch=graphics \
					  --subsystem-nomatch=backlight --subsystem-nomatch=video4linux	--subsystem-nomatch=platform
/sbin/udevadm settle


exit 0
